# name: Data Extraction from RAPID API Yahoo Finance API to S3

# on:
#   workflow_dispatch:  # Manually trigger enabled
#   schedule:
#     - cron: '0 10 * * *'  # Run daily at 10:00 UTC

# env:
#   RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
#   AWS_REGION: ${{ secrets.AWS_REGION }}
#   AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}

# jobs:
#   run-script:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.9

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r scripts/requirements-api-call.txt

#       - name: Run Python script
#         run: python scripts/api_call.py
